### ISSUE TITLE
load spots > process spots for indexing

### ISSUE THREAD

**Issue by junspark** [joelvbernier/hexrd#29]
I picked out the spots using "Add Spots", saved as a cpickle file. I had to step away so I closed everything. I came back later, restarted hexrd, loaded the experiment (material, reader, and detector) then loaded the spots that I had generated. Then used "Process Spots for Indexing" and I got nothing back. The error message was 

IndexError: list index out of range

and "Number of Spots" field in "Spots for indexing" did not change from 0.

**Comment by joelvbernier** [comment]
Spots are deprecated, so this issue is moot.
