### ISSUE TITLE
shape and dtype in processed imageseries

### ISSUE THREAD

**Issue by donald-e-boyce** [joelvbernier/hexrd#61]
The shape and dtype are not set correctly for processed imageseries that alter the shape or dtype. In process.py, the shape and dtype are set from the original imageseries before processing.

**Comment by donald-e-boyce** [comment]
I take that back. Shape is done correctly, but dtype needs to be corrected.

**Comment by joelvbernier** [comment]
Was this ever fixed Don?

**Comment by donald-e-boyce** [comment]
Yes, this was pull request 63 that was merged into your master branch on March 28. The labels are confusing though. Above your comment, it shows "Issue 61 #63" and a purple "merged" box. What happened was that I had a branch named "issue-61" that was merged in pull request 63 and which fixed issue 61.
